version: '3'

services:
  mariadb:
    image: mariadb:10.3.10
    environment:
      MYSQL_ROOT_PASSWORD: myp@ssw0rd
      MYSQL_DATABASE: phpbb
    volumes:
      - ${VOLUME_PATH:-/mnt/data}/{{ index .Service.Labels "com.docker.stack.namespace" }}/mariadb:/var/lib/mysql
    deploy:
      placement:
        constraints: [node.labels.reserved != true]
    networks:
      - internal

  phpbb:
    image: bitnami/phpbb:3.2.5
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - PHPBB_DATABASE_USER=root
      - PHPBB_DATABASE_NAME=phpbb
      - PHPBB_DATABASE_PASSWORD=myp@ssw0rd
      - PHPBB_USERNAME=${PHPBB_USERNAME:-admin}
      - PHPBB_PASSWORD=${PHPBB_PASSWORD:-myp@ssw0rd}
      - PHPBB_EMAIL=${EMAIL:-noreply@ethibox.fr}
    volumes:
      - ${VOLUME_PATH:-/mnt/data}/{{ index .Service.Labels "com.docker.stack.namespace" }}/phpbb:/bitnami
    deploy:
      labels:
        traefik.port: 80
        traefik.frontend.rule: Host:${DOMAIN:?err}
        traefik.enable: "true"
        traefik.docker.network: traefik-net
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 200M
      placement:
        constraints: [node.labels.reserved != true]
    networks:
      - traefik
      - internal

networks:
  internal:
  traefik:
    external:
      name: traefik-net
