version: '3.7'

services:
  prestashop:
    image: prestashop/prestashop:${VERSION:-1.7-7.2-apache}
    volumes:
      - ${VOLUME_PATH}data:/var/www/html:cached
    environment:
      - DB_SERVER=mariadb
      - DB_USER=${MYSQL_USER:-prestashop}
      - DB_PASSWD=${MYSQL_PASSWORD:-myp@ssw0rd}
      - DB_NAME=${MYSQL_DATABASE:-prestashop}
      - PS_DOMAIN=${DOMAIN:-prestashop.localhost}
      - PS_HANDLE_DYNAMIC_DOMAIN=${PS_HANDLE_DYNAMIC_DOMAIN:-1}
      - PS_LANGUAGE=${PS_LANGUAGE:-fr}
      - PS_INSTALL_AUTO=${PS_INSTALL_AUTO:-1}
      - PS_ENABLE_SSL=${PS_ENABLE_SSL:-0}
      - PS_FOLDER_INSTALL=${PS_FOLDER_INSTALL:-install-destroy}
      - PS_FOLDER_ADMIN=${PS_FOLDER_ADMIN:-admin-secure}
      - PS_DEMO_MODE${PS_DEMO_MODE:-1}
      - ADMIN_MAIL=${ADMIN_MAIL:-noreply@ethibox.fr}
      - ADMIN_PASSWD=${ADMIN_PASSWD:-myp@ssw0rd}
    deploy:
      labels:
        - traefik.port=80
        - traefik.enable=true
        - traefik.frontend.rule=Host:${DOMAIN:-prestashop.localhost}
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 200M
    networks:
      - traefik
      - internal

  mariadb:
    image: mariadb:10.3.14
    volumes:
      - ${VOLUME_PATH}mariadb:/var/lib/mysql:cached
    environment:
      - MYSQL_ROOT_PASSWORD=myp@ssw0rd
      - MYSQL_DATABASE=${MYSQL_DATABASE:-prestashop}
      - MYSQL_USER=${MYSQL_USER:-prestashop}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-myp@ssw0rd}
    networks:
      - internal

volumes:
  data:
  mariadb:

networks:
  internal:
  traefik:
    external: true
    name: traefik-net
