version: "3.7"

services:
  traefik:
    image: traefik:${VERSION:-1.7}
    ports:
      - 80:80
    command:
      # - --debug
      # - --loglevel=INFO
      - --entryPoints=Name:http Address::80 Compress:true
      - --defaultEntryPoints=http
      - --docker.swarmmode=true
      - --docker.exposedbydefault=true
      - --docker.network=traefik-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      placement:
        constraints: [node.role==manager]

networks:
  default:
    external: true
    name: traefik-net
