version: '3.7'

services:
  nginx:
    image: ethibox/nginx-proxy:latest
    volumes:
      - ${VOLUME_PATH}wordpress:/var/www/html:cached
    deploy:
      labels:
        - traefik.port=80
        - traefik.enable=true
        - traefik.frontend.rule=Host:${DOMAIN:-wordpress.localhost}
    networks:
      - internal
      - traefik

  app:
    image: wordpress:${VERSION:-5.3.1-fpm-alpine}
    volumes:
      - ${VOLUME_PATH}wordpress:/var/www/html:cached
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=myp@ssw0rd
    deploy:
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 200M
    networks:
      - internal

  mariadb:
    image: mariadb:10.3.14
    volumes:
      - ${VOLUME_PATH}mariadb:/var/lib/mysql:cached
    environment:
      - MYSQL_ROOT_PASSWORD=myp@ssw0rd
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=myp@ssw0rd
    networks:
      - internal

volumes:
  mariadb:
  wordpress:

networks:
  internal:
  traefik:
    external: true
    name: traefik-net
