# sudo sysctl -w vm.max_map_count=262144
# echo "vm.max_map_count=262144" | sudo tee -a /etc/sysctl.conf
# chmod g+rwx esdatadir && chgrp 1000 esdatadir

version: '3.7'

services:
  zammad-elasticsearch:
    image: zammad/zammad-docker-compose:zammad-elasticsearch-${VERSION:-3.2.0-6}
    volumes:
      - ${VOLUME_PATH}elasticsearch:/usr/share/elasticsearch/data
    networks:
      - internal

  zammad-init:
    image: zammad/zammad-docker-compose:zammad-${VERSION:-3.2.0-6}
    command: ["zammad-init"]
    volumes:
      - ${VOLUME_PATH}zammad:/opt/zammad
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - internal

  zammad-memcached:
    image: zammad/zammad-docker-compose:zammad-memcached-${VERSION:-3.2.0-6}
    command: ["zammad-memcached"]
    networks:
      - internal

  zammad-nginx:
    image: zammad/zammad-docker-compose:zammad-${VERSION:-3.2.0-6}
    command: ["zammad-nginx"]
    volumes:
      - ${VOLUME_PATH}zammad:/opt/zammad
    deploy:
      labels:
        - traefik.port=80
        - traefik.enable=true
        - traefik.frontend.rule=Host:${DOMAIN:-zammad.localhost}
    networks:
      - traefik
      - internal

  zammad-postgresql:
    image: zammad/zammad-docker-compose:zammad-postgresql-${VERSION:-3.2.0-6}
    volumes:
      - ${VOLUME_PATH}postgresql:/var/lib/postgresql/data
    networks:
      - internal

  zammad-railsserver:
    image: zammad/zammad-docker-compose:zammad-${VERSION:-3.2.0-6}
    command: ["zammad-railsserver"]
    volumes:
      - ${VOLUME_PATH}zammad:/opt/zammad
    networks:
      - internal

  zammad-scheduler:
    image: zammad/zammad-docker-compose:zammad-${VERSION:-3.2.0-6}
    command: ["zammad-scheduler"]
    volumes:
      - ${VOLUME_PATH}zammad:/opt/zammad
    networks:
      - internal

  zammad-websocket:
    image: zammad/zammad-docker-compose:zammad-${VERSION:-3.2.0-6}
    command: ["zammad-websocket"]
    volumes:
      - ${VOLUME_PATH}zammad:/opt/zammad
    networks:
      - internal

volumes:
  zammad:
  elasticsearch:
  postgresql:

networks:
  internal:
  traefik:
    external: true
    name: traefik-net
